### ISSUE TITLE
Session: Starting Screen

### ISSUE THREAD

**Issue by kantacky** [kantacky/strayit-ios#101]

**Comment by kantacky** [comment]
@nanosuke どういうアニメーションを想定してる？

**Comment by nanosuke** [comment]
<img width="238" alt="image" src="https://github.com/kantacky/strayit-ios/assets/82511590/ea3e310c-2792-4bdf-8da5-50b05f1fe3c4">

・画面x:中央,y:-6にあるspaceshipが、画面中央に移動するアニメーション
・セッションスタート後2000ms後にアニメーションが始まる
・イーズイン・アウトで1000msのアニメーション

この情報でコード書ける要件満たしてる？？swiftのアニメーション勉強しようと思って全然してないわ

**Comment by kantacky** [comment]
ありがとう！やってみる！僕もよくわかってない！
