### ISSUE TITLE
App Navigation

### ISSUE THREAD

**Issue by kantacky** [kantacky/strayit-ios#6]
Search, Direction, Adventure, Cheating, AppInfo のナビゲーション

**Comment by nanosuke** [comment]
<img width="465" alt="image" src="https://github.com/kantacky/strayit-ios/assets/82511590/ea16d498-c024-4617-9d4e-8f8e896ed9a9">
Searchビュー
テキストフィールドにフォーカスしたら検索マークが戻るボタンに
