### ISSUE TITLE
Design: Semantic Color

### ISSUE THREAD

**Issue by kantacky** [kantacky/strayit-ios#63]

**Comment by nanosuke** [comment]
@nanosuke ライトモード時の色について未完成です

**Comment by kantacky** [comment]
> [@nanosuke](https://github.com/nanosuke) ライトモード時の色について未完成です
@nanosuke 
完成予定は？
とりあえずDarkだけすすめるけど、
そのままだとLightの見た目がおかしいはず (実装しないと良くわからん) だから、
ベータ版までにLightモードをDisableするかアップデートする必要があるね〜

**Comment by nanosuke** [comment]
@kantacky 6/10(月)中までにやるわ！

**Comment by kantacky** [comment]
おわったら、またAssignしてください！
