### ISSUE TITLE
Search: Result Ordering

### ISSUE THREAD

**Issue by nanosuke** [kantacky/strayit-ios#67]
![IMG_3576](https://github.com/kantacky/strayit-ios/assets/82511590/6834eb9f-1f05-43a1-a4d4-512b164c8a23)
Searchビューの検索予測について、ユーザーの現在地に近い順に結果を表示するのってできる？
画像の例：シエスタハコダテや五稜郭のスタバが上の方に出てくるように

**Comment by kantacky** [comment]
距離を表示する実装をすればできるよー
