### ISSUE TITLE
Session: Ignore SafeArea

### ISSUE THREAD

**Issue by nanosuke** [kantacky/strayit-ios#96]
https://github.com/kantacky/strayit-ios/assets/82511590/b96b880a-1921-452b-a2d4-f507009847d8

**Comment by kantacky** [comment]
動画わかりやすい、ありがとう
これは、キーボードが閉じるモーションがあるからしょうがないっちゃしょうがないんだけど...
ちょっと検討します

**Comment by kantacky** [comment]
`.ignoreSafeArea()` でなんとかならんかな

**Comment by kantacky** [comment]
確認画面を作れば不要
